### ISSUE TITLE
Fix qa-ctl tool error executions

### ISSUE THREAD

**Issue by fernandolojano** [wazuh/wazuh-qa#2182]
While testing some use cases for the qa-ctl tool, the execution of the command `qa-ctl -r test_cors test_cache --qa-branch 2173-qa-ctl-v2-release --dry-run -dd` ended up with the next error output:

<details>
  <summary>test_cors & test_cache error</summary>

  ```
qa-ctl -r test_cors test_cache --qa-branch 2173-qa-ctl-v2-release --dry-run -dd
2021-11-05 12:44:18,402 - DEBUG - Downloading 2173-qa-ctl-v2-release files of wazuh-qa repository in /tmp/wazuh_qa_ctl/wazuh-qa
2021-11-05 12:44:19,887 - INFO - Validating input parameters
2021-11-05 12:44:21,845 - INFO - Input parameters validation has passed successfully
2021-11-05 12:44:21,845 - DEBUG - Generating configuration file
Traceback (most recent call last):
  File "/home/reko/repos/testing-qactl/testing-linux/bin/qa-ctl", line 33, in <module>
    sys.exit(load_entry_point('wazuh-testing==4.3.0', 'console_scripts', 'qa-ctl')())
  File "/home/reko/repos/testing-qactl/testing-linux/lib/python3.8/site-packages/wazuh_testing-4.3.0-py3.8.egg/wazuh_testing/scripts/qa_ctl.py", line 332, in main
    config_generator.run()
  File "/home/reko/repos/testing-qactl/testing-linux/lib/python3.8/site-packages/wazuh_testing-4.3.0-py3.8.egg/wazuh_testing/qa_ctl/configuration/config_generator.py", line 550, in run
    self.__process_test_info(info)
  File "/home/reko/repos/testing-qactl/testing-linux/lib/python3.8/site-packages/wazuh_testing-4.3.0-py3.8.egg/wazuh_testing/qa_ctl/configuration/config_generator.py", line 536, in __process_test_info
    self.__process_test_data(tests_info)
  File "/home/reko/repos/testing-qactl/testing-linux/lib/python3.8/site-packages/wazuh_testing-4.3.0-py3.8.egg/wazuh_testing/qa_ctl/configuration/config_generator.py", line 517, in __process_test_data
    self.__set_testing_config(tests_info)
  File "/home/reko/repos/testing-qactl/testing-linux/lib/python3.8/site-packages/wazuh_testing-4.3.0-py3.8.egg/wazuh_testing/qa_ctl/configuration/config_generator.py", line 483, in __set_testing_config
    vm_box = self.config['deployment'][instance]['provider']['vagrant']['vagrant_box']
KeyError: 'host_3'
  ```
  </details>

It is needed to investigate and solve the reason of the failure of this execution

**Comment by jmv74211** [comment]
This commit https://github.com/wazuh/wazuh-qa/commit/385078ae686573c610dbf94eba228bcf3d1e67e7 fixes it
