### ISSUE TITLE
`Generate artifacts` step failing when `remote` option is selected

### ISSUE THREAD

**Issue by yanazaeva** [wazuh/wazuh-qa#2195]
Hey team,

Apparently, sometimes when you run the `test_cluster_performance` or the `CLUSTER-Workload_benchmarks_metrics` pipelines, the execution fails in the `Generate artifacts` step due to the following error: 
```
chown: cannot access '/mnt/efs/tmp/Test_cluster_performance/B_271/i-Test_cluster_performance_B271_manager_0/plots/stats/wazuh-remote*': No such file or directory
```

This happens when the option **remote** is selected within the **MANAGER_MONITORING_STATS** menu. 

Regards.

**Comment by jmv74211** [comment]
Related to https://github.com/wazuh/wazuh-jenkins/issues/3053

**Comment by jmv74211** [comment]
I seem to have found the cause of the error.

The graphs corresponding to the remoted statistics seem to be not being generated correctly, and when trying to group for Jenkins artifacts, it fails to find them.

The cause of not being able to generate the images, is that the `data_visualizations.py` script returns the following error:

```
2021-11-11T11:45:59.939+01:00	The above exception was the direct cause of the following exception:
2021-11-11T11:45:59.939+01:00	Traceback (most recent call last):
2021-11-11T11:45:59.939+01:00	File "/usr/local/bin/data-visualizer", line 33, in <module>
2021-11-11T11:45:59.939+01:00	sys.exit(load_entry_point('wazuh-testing==4.3.0', 'console_scripts', 'data-visualizer')())
2021-11-11T11:45:59.939+01:00	File "/usr/local/lib/python3.9/site-packages/wazuh_testing-4.3.0-py3.9.egg/wazuh_testing/scripts/data_visualizations.py", line 33, in main
2021-11-11T11:45:59.939+01:00	dv.plot()
2021-11-11T11:45:59.939+01:00	File "/usr/local/lib/python3.9/site-packages/wazuh_testing-4.3.0-py3.9.egg/wazuh_testing/tools/performance/visualization.py", line 298, in plot
2021-11-11T11:45:59.939+01:00	self._plot_remoted_dataset()
2021-11-11T11:45:59.939+01:00	File "/usr/local/lib/python3.9/site-packages/wazuh_testing-4.3.0-py3.9.egg/wazuh_testing/tools/performance/visualization.py", line 262, in _plot_remoted_dataset
2021-11-11T11:45:59.939+01:00	self._plot_data(elements=columns, title=title, generic_label=element)
2021-11-11T11:45:59.939+01:00	File "/usr/local/lib/python3.9/site-packages/wazuh_testing-4.3.0-py3.9.egg/wazuh_testing/tools/performance/visualization.py", line 242, in _plot_data
2021-11-11T11:45:59.939+01:00	self._basic_plot(ax, self.dataframe[element], label=element, color=color)
2021-11-11T11:45:59.939+01:00	File "/usr/local/lib/python3.9/site-packages/pandas/core/frame.py", line 3024, in __getitem__
2021-11-11T11:45:59.940+01:00	indexer = self.columns.get_loc(key)
2021-11-11T11:45:59.940+01:00	File "/usr/local/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3082, in get_loc
2021-11-11T11:45:59.941+01:00	raise KeyError(key) from err
2021-11-11T11:45:59.941+01:00	KeyError: 'msg_sent'
```

I will investigate this case and make the following modifications:

- Investigate and fix the `KeyError: 'msg_sent'` error in the `data_visualizations.py` script.
- Control exception of files not found when generating the artifacts so that the build does not fail and the results can be collected.

**Comment by jmv74211** [comment]
I think I have found the root of the problem. The `wazuh-remoted.state` statistics are different from `4.3.0` to `4.2.4`.

**4.2.4**

```
# Queue size
queue_size='0'

# Total queue size
total_queue_size='131072'

# TCP sessions
tcp_sessions='0'

# Events sent to Analysisd
evt_count='0'

# Control messages received
ctrl_msg_count='0'

# Discarded messages
discarded_count='0'

# Messages sent
msg_sent='0'

# Total number of bytes received
recv_bytes='0'

# Messages dequeued after the agent closes the connection
dequeued_after_close='0' 
```

**4.3**

```
# Queue size
queue_size='0'

# Total queue size
total_queue_size='131072'

# TCP sessions
tcp_sessions='0'

# Events sent to Analysisd
evt_count='0'

# Control messages received
ctrl_msg_count='0'

# Discarded messages
discarded_count='0'

# Messages queued
queued_msgs='0'

# Total number of bytes sent
sent_bytes='0'

# Total number of bytes received
recv_bytes='0'

# Messages dequeued after the agent closes the connection
dequeued_after_close='0'
```

Basically the difference is as follows:
- **4.2.4** --> `msg_sent='0'`
- **4.3.0** --> Two new fields appear `queued_msgs='0'` and `sent_bytes='0'` and `msg_sent='0'` disappears.

I will check with the development team if this change is foreseen, and if so, we will have to open issue to make the corresponding changes in the QA monitoring and visualization tools.
