### ISSUE TITLE
Add integration tests for remaining API middleware functions

### ISSUE THREAD

**Issue by mcarmona99** [wazuh/wazuh-qa#2576]
## Description

As it was said in https://github.com/wazuh/wazuh/issues/10392#issuecomment-945443443, there are API middlewares that have way too specific functionality, making their related unit tests pointless. In the wazuh-qa repository, we already have integration tests for the [brute force blocking system](https://github.com/wazuh/wazuh-qa/tree/master/tests/integration/test_api/test_config/test_bruteforce_blocking_system), and for the [DOS blocking system](https://github.com/wazuh/wazuh-qa/tree/master/tests/integration/test_api/test_config/test_DOS_blocking_system) middlewares.

This issue aims to add new integration tests to check that all the API middlewares are working properly. The functions to be tested will be the ones that don't have unit tests: `set_secure_headers`, `request_logging`, and `response_postprocessing`.

#### `set_secure_headers`: middleware used to add API secure headers to responses.

[api/api/middlewares.py#L36-L40](https://github.com/wazuh/wazuh/blob/3ccbe4295340d615275da753c98f36b6c23ca719/api/api/middlewares.py#L36-L40
)

```python
@web.middleware
async def set_secure_headers(request, handler):
    resp = await handler(request)
    secure_headers.aiohttp(resp)
    return resp
```

Test cases:
- make a request -> check that the response headers are the expected ones (more info https://github.com/wazuh/wazuh/issues/7024)

#### `request_logging`: middleware used to add request info to API logs. It also saves the body in the request instance.

[api/api/middlewares.py#L80-L90](https://github.com/wazuh/wazuh/blob/3ccbe4295340d615275da753c98f36b6c23ca719/api/api/middlewares.py#L80-L90)

```python
@web.middleware
async def request_logging(request, handler):
    """Add request info to logging."""
    logger.debug2(f'Receiving headers {dict(request.headers)}')
    try:
        body = await request.json()
        request['body'] = body
    except JSONDecodeError:
        pass

    return await handler(request)
```

Test cases:
- make a request with debug mode = 2 -> check the request headers are logged
- make a request with JSON body -> body logged
- make a request without JSON body -> no body logged (default={})

#### `response_postprocessing`: middleware used to remove unwanted fields from error responses. It also cleans the output given by `connexion` exceptions.

[api/api/middlewares.py#L121-L166](https://github.com/wazuh/wazuh/blob/3ccbe4295340d615275da753c98f36b6c23ca719/api/api/middlewares.py#L121-L166)

```python
@web.middleware
async def response_postprocessing(request, handler):
    """Remove unwanted fields from error responses like 400 or 403.
    Additionally, it cleans the output given by connexion's exceptions. If no exception is raised during the
    'await handler(request) it means the output will be a 200 response and no fields needs to be removed."""

    def remove_unwanted_fields(fields_to_remove=None):
        fields_to_remove = fields_to_remove or ['status', 'type']
        for field in fields_to_remove:
            if field in problem.body:
                del problem.body[field]
        if problem.body.get('detail') == '':
            del problem.body['detail']
        if 'code' in problem.body:
            problem.body['error'] = problem.body.pop('code')

    problem = None

    try:
        return await handler(request)

    except ProblemException as ex:
        problem = connexion_problem(status=ex.__dict__['status'],
                                    title=ex.__dict__['title'] if ex.__dict__.get('title') else 'Bad Request',
                                    type=ex.__dict__.get('type', 'about:blank'),
                                    detail=_cleanup_detail_field(ex.__dict__['detail'])
                                    if 'detail' in ex.__dict__ else '',
                                    ext=ex.__dict__.get('ext'))
    except HTTPException as ex:
        problem = connexion_problem(ex.status,
                                    ex.reason if ex.reason else '',
                                    type=ex.reason if ex.reason else '',
                                    detail=ex.text if ex.text else '')
    except (OAuthProblem, Unauthorized):
        if request.path in {'/security/user/authenticate', '/security/user/authenticate/run_as'} and \
                request.method in {'GET', 'POST'}:
            await prevent_bruteforce_attack(request=request, attempts=api_conf['access']['max_login_attempts'])
            problem = connexion_problem(401, "Unauthorized", type="about:blank", detail="Invalid credentials")
        else:
            problem = connexion_problem(401, "Unauthorized", type="about:blank",
                                        detail="No authorization token provided")
    finally:
        problem and remove_unwanted_fields()

    return problem
```

Test cases:
- make a request returning a 400 code -> validate response fields
- make a request returning a 404 code (endpoint not found) -> validate response fields
- make a request without having logged in before -> connexion_problem created, validate specific detail
- make a request to login with wrong credentials -> connexion_problem created, validate specific detail

For all the last test cases, check that the `status` and `type` fields are removed in the response; if there is `detail`, it is not empty; and the `code` field is removed and an `error` field created. In other words, test the `remove_unwanted_fields` function.

**Comment by davidjiglesias** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wazuh---Framework-5d8b5184022c8d0001c05f4d/issues/wazuh/wazuh-qa/2576?planning-poker) with ZenHub @Kondent @mcarmona99 @vicferpoy

**Comment by mcarmona99** [comment]
## Issue update

Right now, all QA API integration tests are failing in the **wazuh** and **wazuh-qa** `master` branches:

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 269, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 322, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 333, in pytest_collection
INTERNALERROR>     session.perform_collect()
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 638, in perform_collect
INTERNALERROR>     session=self, config=self.config, items=items
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/vagrant/wazuh-qa/tests/integration/conftest.py", line 65, in pytest_collection_modifyitems
INTERNALERROR>     elif item.config.getoption("--tier-minimum") > levels[0]:
INTERNALERROR> IndexError: list index out of range
```

This error has been reported to the QA team and an issue to solve it has been opened: https://github.com/wazuh/wazuh-qa/issues/2714

This issue will be blocked until #2714 is solved.
