### ISSUE TITLE
Release 4.3.0 - Manual tests - Deployment with Ansible

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#2821]
The following issue aims to run the specified test for the current release candidate, report the results, and open new issues for any encountered errors.

## Test information
|                         |                                            |
|-------------------------|--------------------------------------------|
| **Test name**           |   Deployment with Ansible                                         |
| **Category**            |     Installation                                       |
| **Deployment option**   |    Ansible                                        |
| **Main release issue**  |     https://github.com/wazuh/wazuh/issues/10954                                       |
| **Release candidate #** |     RC6                                       |

## Test description
- [x] Test distributed deployment with Wazuh manager cluster and Wazuh indexer cluster via ansible.
  - [x] Deploy a distributed environment. 
  - [x] Once a distributed environment is active, launch again the playbook changing the credentials.
- [x] Test deployment of an agent via ansible.

## Test report procedure

All test results must have one of the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:    | There is at least one failed result. |
| :yellow_circle:  | There is at least one expected failure or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. 

An extended report of the test results must be attached as a ZIP or TXT file. Please attach any documents, screenshots, or tables to the issue update with the results. This report can be used by the auditors to dig deeper into any possible failures and details.

## Conclusions

All tests have been executed and the results can be found [here]().

|                |             |                     |                |
|----------------|-------------|---------------------|----------------|
| **Status**     | **Test**    | **Failure type**    | **Notes**      |
|  :yellow_circle:     | Test distributed deployment with Wazuh manager cluster and Wazuh indexer cluster via ansible. |  |  |
|  :green_circle:   | Test deployment of a agent via ansible. | |  |

## Reported issues

| Issue                                                            | Description                                                                  | Severity |
|------------------------------------------------------------------|------------------------------------------------------------------------------|-----------
|      https://github.com/wazuh/wazuh-documentation/issues/5132   |       Include sudo to sshd restarting command       |   Low   |
| https://github.com/wazuh/wazuh-ansible/issues/754 |  Dashboard is installed along with indexer   | Medium |
| https://github.com/wazuh/wazuh-ansible/issues/755  | Provision playbook in an active distributed environment fail | Low | 

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [x] @alberpilot 
- [x] @jmv74211

**Comment by Rebits** [comment]
### 25/04/2022

# Install Ansible
All tests have been performed in a centOS 8

## Installation on CentOS/RHEL/Fedora
<details>
<summary> Install EPEL repository </summary>

```
[root@centos vagrant]# yum -y install epel-release
CentOS Linux 8 - A  11 kB/s | 4.3 kB     00:00    
CentOS Linux 8 - B  21 kB/s | 3.9 kB     00:00    
CentOS Linux 8 - E 7.8 kB/s | 1.5 kB     00:00    
Extra Packages for  40 kB/s |  32 kB     00:00    
Extra Packages for 1.0 MB/s | 1.0 MB     00:01    
Extra Packages for  50 kB/s |  30 kB     00:00    
Extra Packages for 3.7 MB/s |  11 MB     00:02    
Module yaml error: Unexpected key in data: static_context [line 9 col 3]
Module yaml error: Unexpected key in data: static_context [line 9 col 3]
Package epel-release-8-11.el8.noarch is already installed.
Dependencies resolved.
===================================================
 Package        Arch     Version      Repo    Size
===================================================
Upgrading:
 epel-release   noarch   8-15.el8     epel    23 k

Transaction Summary
===================================================
Upgrade  1 Package

Total download size: 23 k
Downloading Packages:
epel-release-8-15. 182 kB/s |  23 kB     00:00    
---------------------------------------------------
Total               33 kB/s |  23 kB     00:00     
warning: /var/cache/dnf/epel-6c12381928511f32/packages/epel-release-8-15.el8.noarch.rpm: Header V4 RSA/SHA256 Signature, key ID 2f86d6a1: NOKEY
Extra Packages for 791 kB/s | 1.6 kB     00:00    
Importing GPG key 0x2F86D6A1:
 Userid     : "Fedora EPEL (8) <epel@fedoraproject.org>"
 Fingerprint: 94E2 79EB 8D8F 25B2 1810 ADF1 21EA 45AB 2F86 D6A1
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-8
Key imported successfully
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                           1/1 
  Running scriptlet: epel-release-8-15.el8.n   1/1 
  Upgrading        : epel-release-8-15.el8.n   1/2 
  Cleanup          : epel-release-8-11.el8.n   2/2 
  Running scriptlet: epel-release-8-11.el8.n   2/2 
  Verifying        : epel-release-8-15.el8.n   1/2 
  Verifying        : epel-release-8-11.el8.n   2/2 

Upgraded:
  epel-release-8-15.el8.noarch                     

Complete!
```
</details>

<details>

<summary> Install ansible </summary>

```
[root@centos vagrant]# yum install ansible
Last metadata expiration check: 0:00:32 ago on Mon 25 Apr 2022 09:26:04 UTC.
Module yaml error: Unexpected key in data: static_context [line 9 col 3]
Module yaml error: Unexpected key in data: static_context [line 9 col 3]
Dependencies resolved.
===================================================
 Package       Arch   Version      Repo       Size
===================================================
Installing:
 ansible       noarch 2.9.27-1.el8 epel       17 M
Installing dependencies:
 libsodium     x86_64 1.0.18-2.el8 epel      162 k
 python3-babel noarch 2.5.1-7.el8  appstream 4.8 M
 python3-bcrypt
               x86_64 3.1.6-2.el8.1
                                   epel       44 k
 python3-cffi  x86_64 1.11.5-5.el8 baseos    237 k
 python3-cryptography
               x86_64 3.2.1-5.el8  baseos    559 k
 python3-jinja2
               noarch 2.10.1-3.el8 appstream 538 k
 python3-jmespath
               noarch 0.9.0-11.el8 appstream  45 k
 python3-markupsafe
               x86_64 0.23-19.el8  appstream  39 k
 python3-ply   noarch 3.9-9.el8    baseos    111 k
 python3-pyasn1
               noarch 0.3.7-6.el8  appstream 126 k
 python3-pycparser
               noarch 2.14-14.el8  baseos    109 k
 python3-pynacl
               x86_64 1.3.0-5.el8  epel      100 k
 python3-pytz  noarch 2017.2-9.el8 appstream  54 k
 sshpass       x86_64 1.06-9.el8   epel       27 k
Installing weak dependencies:
 python3-paramiko
               noarch 2.4.3-2.el8  epel      290 k

Transaction Summary
===================================================
Install  16 Packages

Total download size: 24 M
Installed size: 126 M
Is this ok [y/N]: y
Downloading Packages:
(1/16): python3-jmespath-0.9.0-11.el8.noarch.rpm                         49 kB/s |  45 kB     00:00    
(2/16): python3-markupsafe-0.23-19.el8.x86_64.rpm                       103 kB/s |  39 kB     00:00    
(3/16): python3-pyasn1-0.3.7-6.el8.noarch.rpm                           186 kB/s | 126 kB     00:00    
(4/16): python3-jinja2-2.10.1-3.el8.noarch.rpm                          259 kB/s | 538 kB     00:02    
(5/16): python3-pytz-2017.2-9.el8.noarch.rpm                             95 kB/s |  54 kB     00:00    
(6/16): python3-cffi-1.11.5-5.el8.x86_64.rpm                            196 kB/s | 237 kB     00:01    
(7/16): python3-ply-3.9-9.el8.noarch.rpm                                169 kB/s | 111 kB     00:00    
(8/16): python3-cryptography-3.2.1-5.el8.x86_64.rpm                     328 kB/s | 559 kB     00:01    
(9/16): python3-pycparser-2.14-14.el8.noarch.rpm                        216 kB/s | 109 kB     00:00    
(10/16): libsodium-1.0.18-2.el8.x86_64.rpm                               92 kB/s | 162 kB     00:01    
(11/16): python3-bcrypt-3.1.6-2.el8.1.x86_64.rpm                        169 kB/s |  44 kB     00:00    
(12/16): python3-paramiko-2.4.3-2.el8.noarch.rpm                        132 kB/s | 290 kB     00:02    
(13/16): python3-pynacl-1.3.0-5.el8.x86_64.rpm                          129 kB/s | 100 kB     00:00    
(14/16): sshpass-1.06-9.el8.x86_64.rpm                                  197 kB/s |  27 kB     00:00    
(15/16): python3-babel-2.5.1-7.el8.noarch.rpm                           502 kB/s | 4.8 MB     00:09    
(16/16): ansible-2.9.27-1.el8.noarch.rpm                                1.2 MB/s |  17 MB     00:13    
--------------------------------------------------------------------------------------------------------
Total                                                                   1.3 MB/s |  24 MB     00:18     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                1/1 
  Installing       : sshpass-1.06-9.el8.x86_64                                                     1/16 
  Installing       : libsodium-1.0.18-2.el8.x86_64                                                 2/16 
  Installing       : python3-ply-3.9-9.el8.noarch                                                  3/16 
  Installing       : python3-pycparser-2.14-14.el8.noarch                                          4/16 
  Installing       : python3-cffi-1.11.5-5.el8.x86_64                                              5/16 
  Installing       : python3-cryptography-3.2.1-5.el8.x86_64                                       6/16 
  Installing       : python3-bcrypt-3.1.6-2.el8.1.x86_64                                           7/16 
  Installing       : python3-pynacl-1.3.0-5.el8.x86_64                                             8/16 
  Installing       : python3-pytz-2017.2-9.el8.noarch                                              9/16 
  Installing       : python3-babel-2.5.1-7.el8.noarch                                             10/16 
  Installing       : python3-pyasn1-0.3.7-6.el8.noarch                                            11/16 
  Installing       : python3-paramiko-2.4.3-2.el8.noarch                                          12/16 
  Installing       : python3-markupsafe-0.23-19.el8.x86_64                                        13/16 
  Installing       : python3-jinja2-2.10.1-3.el8.noarch                                           14/16 
  Installing       : python3-jmespath-0.9.0-11.el8.noarch                                         15/16 
  Installing       : ansible-2.9.27-1.el8.noarch                                                  16/16 
  Running scriptlet: ansible-2.9.27-1.el8.noarch                                                  16/16 
  Verifying        : python3-babel-2.5.1-7.el8.noarch                                              1/16 
  Verifying        : python3-jinja2-2.10.1-3.el8.noarch                                            2/16 
  Verifying        : python3-jmespath-0.9.0-11.el8.noarch                                          3/16 
  Verifying        : python3-markupsafe-0.23-19.el8.x86_64                                         4/16 
  Verifying        : python3-pyasn1-0.3.7-6.el8.noarch                                             5/16 
  Verifying        : python3-pytz-2017.2-9.el8.noarch                                              6/16 
  Verifying        : python3-cffi-1.11.5-5.el8.x86_64                                              7/16 
  Verifying        : python3-cryptography-3.2.1-5.el8.x86_64                                       8/16 
  Verifying        : python3-ply-3.9-9.el8.noarch                                                  9/16 
  Verifying        : python3-pycparser-2.14-14.el8.noarch                                         10/16 
  Verifying        : ansible-2.9.27-1.el8.noarch                                                  11/16 
  Verifying        : libsodium-1.0.18-2.el8.x86_64                                                12/16 
  Verifying        : python3-bcrypt-3.1.6-2.el8.1.x86_64                                          13/16 
  Verifying        : python3-paramiko-2.4.3-2.el8.noarch                                          14/16 
  Verifying        : python3-pynacl-1.3.0-5.el8.x86_64                                            15/16 
  Verifying        : sshpass-1.06-9.el8.x86_64                                                    16/16 

Installed:
  ansible-2.9.27-1.el8.noarch                       libsodium-1.0.18-2.el8.x86_64                      
  python3-babel-2.5.1-7.el8.noarch                  python3-bcrypt-3.1.6-2.el8.1.x86_64                
  python3-cffi-1.11.5-5.el8.x86_64                  python3-cryptography-3.2.1-5.el8.x86_64            
  python3-jinja2-2.10.1-3.el8.noarch                python3-jmespath-0.9.0-11.el8.noarch               
  python3-markupsafe-0.23-19.el8.x86_64             python3-paramiko-2.4.3-2.el8.noarch                
  python3-ply-3.9-9.el8.noarch                      python3-pyasn1-0.3.7-6.el8.noarch                  
  python3-pycparser-2.14-14.el8.noarch              python3-pynacl-1.3.0-5.el8.x86_64                  
  python3-pytz-2017.2-9.el8.noarch                  sshpass-1.06-9.el8.x86_64                          

Complete!
```

</details>



## Remote connection


<details>

<summary> SSH key-paring </summary>

```
[root@centos ~]# ssh-keygen
Generating public/private rsa key pair.
Enter file in which to save the key (/root/.ssh/id_rsa):       
Created directory '/root/.ssh'.
Enter passphrase (empty for no passphrase): 
Enter same passphrase again: 
Your identification has been saved in /root/.ssh/id_rsa.
Your public key has been saved in /root/.ssh/id_rsa.pub.
The key fingerprint is:
SHA256:6os/G/bQ4fjzloO8QabYDixtpmr4PCYaxQ8ZTU+WUv0 root@centos
The key's randomart image is:
+---[RSA 3072]----+
|    ..+o         |
|   o.+. .        |
|  . ...  .       |
| . o      E      |
|  =     S        |
| . = o O .       |
|o . O O.+. .     |
|o+o= *.=+.+      |
|==+...*++=..     |
+----[SHA256]-----+
[root@centos ~]# ls -la ~/.ssh
total 8
drwx------  2 root root   38 Apr 25 09:46 .
dr-xr-x---. 4 root root  222 Apr 25 09:45 ..
-rw-------  1 root root 2655 Apr 25 09:46 id_rsa
-rw-r--r--  1 root root  565 Apr 25 09:46 id_rsa.pub
```

</details>

<details>

<summary> Testing ansible configuration </summary>

```
[root@centos roles]# ssh vagrant@192.168.56.4
Last login: Mon Apr 25 11:28:52 2022 from 192.168.56.2
[vagrant@centos-manager-1 ~]$ 
```

</details>

<details>

<summary> Playbooks and roles </summary>

```
[root@centos roles]# sudo git clone --branch 4.3 https://github.com/wazuh/wazuh-ansible.git
Cloning into 'wazuh-ansible'...
remote: Enumerating objects: 16158, done.
remote: Counting objects: 100% (3109/3109), done.
remote: Compressing objects: 100% (972/972), done.
remote: Total 16158 (delta 1925), reused 2960 (delta 1838), pack-reused 13049
Receiving objects: 100% (16158/16158), 5.53 MiB | 5.07 MiB/s, done.
Resolving deltas: 100% (10091/10091), done.
```

</details>


## Testing ansible connection to remote endpoints

<details>

<summary> Attempt a connection with the remote endpoints using ping module </summary>

```
[root@centos vagrant]# ansible all -m ping
[WARNING]: Invalid characters were found in group names but not replaced, use
-vvvv to see details
192.168.56.4 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/libexec/platform-python"
    },
    "changed": false,
    "ping": "pong"
}
```

</details>

## Playbooks and roles

<details>

 <summary> Wazuh Ansible cloning </summary>

```
[root@centos roles]# sudo git clone --branch 4.3 https://github.com/wazuh/wazuh-ansible.git
Cloning into 'wazuh-ansible'...
remote: Enumerating objects: 16158, done.
remote: Counting objects: 100% (3109/3109), done.
remote: Compressing objects: 100% (972/972), done.
remote: Total 16158 (delta 1925), reused 2960 (delta 1838), pack-reused 13049
Receiving objects: 100% (16158/16158), 5.53 MiB | 5.07 MiB/s, done.
Resolving deltas: 100% (10091/10091), done.
```

</details>

**Comment by Rebits** [comment]
### 27/04/2022

# Run provision playbook in an active distributed environment :red_circle: 
The `wazuh-production-ready.yml` should be able to skip every task that is already fulfilled in the system. Also, in case we want to change the credentials of our indexer cluster we should be able to do that by removing the credentials folder `/etc/ansible/roles/wazuh-ansible/playbooks/indexer/certificates/` and launching again the playbook.

However the `Initialize the Opensearch security index in Wazuh indexe` will never stop. This is due to indexer `node-6` (dashboard host) does not initialize correctly:
```
Caused by: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
        at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:369) ~[?:?]
        at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:275) ~[?:?]
        at sun.security.validator.Validator.validate(Validator.java:264) ~[?:?]
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:285) ~[?:?]
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:144) ~[?:?]
        at sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1335) ~[?:?]
        at sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1232) ~[?:?]
        at sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1175) ~[?:?]
        at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396) ~[?:?]
        at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480) ~[?:?]
        at sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1267) ~[?:?]
        at sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1254) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:691) ~[?:?]
        at sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1199) ~[?:?]
        at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1547) ~[netty-handler-4.1.72.Final.jar:4.1.72.Final]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1393) ~[netty-handler-4.1.72.Final.jar:4.1.72.Final]
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1234) ~[netty-handler-4.1.72.Final.jar:4.1.72.Final]
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1283) ~[netty-handler-4.1.72.Final.jar:4.1.72.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) ~[netty-codec-4.1.72.Final.jar:4.1.72.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446) ~[netty-codec-4.1.72.Final.jar:4.1.72.Final]
        ... 16 more
Caused by: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
        at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:158) ~[?:?]
        at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:84) ~[?:?]
        at java.security.cert.CertPathValidator.validate(CertPathValidator.java:309) ~[?:?]
        at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:364) ~[?:?]
        at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:275) ~[?:?]
        at sun.security.validator.Validator.validate(Validator.java:264) ~[?:?]
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:285) ~[?:?]
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:144) ~[?:?]
        at sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1335) ~[?:?]
        at sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1232) ~[?:?]
        at sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1175) ~[?:?]
        at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396) ~[?:?]
        at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480) ~[?:?]
        at sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1267) ~[?:?]
        at sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1254) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:691) ~[?:?]
        at sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1199) ~[?:?]
        at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1547) ~[netty-handler-4.1.72.Final.jar:4.1.72.Final]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1393) ~[netty-handler-4.1.72.Final.jar:4.1.72.Final]
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1234) ~[netty-handler-4.1.72.Final.jar:4.1.72.Final]
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1283) ~[netty-handler-4.1.72.Final.jar:4.1.72.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) ~[netty-codec-4.1.72.Final.jar:4.1.72.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446) ~[netty-codec-4.1.72.Final.jar:4.1.72.Final]
        ... 16 more
```

If we list the indexer nodes we can check that this node does not appear anymore
```
[centos@ip-172-31-91-30 ~]$ curl -k -u admin:changeme https://172.31.91.30:9200/_cat/nodes?v
ip           heap.percent ram.percent cpu load_1m load_5m load_15m node.role master name
172.31.91.30           45          89   1    0.00    0.04     0.11 dimr      -      node-1
172.31.84.22           24          88   2    0.00    0.06     0.15 dimr      *      node-3
172.31.86.71            6          90   1    0.00    0.05     0.12 dimr      -      node-2

```

**Comment by Rebits** [comment]
### 27/04/2022
__work_in_progress__
# Test deployment of a agent via ansible. :green_circle: 

```
[root@ip-172-31-83-43 centos]# /var/ossec/bin/agent_control -l

Wazuh agent_control. List of available agents:
   ID: 000, Name: ip-172-31-83-43.ec2.internal (server), IP: 127.0.0.1, Active/Local
   ID: 001, Name: ip-172-31-85-113.ec2.internal, IP: any, Active

List of agentless devices:
```
