### ISSUE TITLE
Adapt QA framework requirements for python3.10

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#2991]
### Description
New nodes and instances are provided with `python3.10.4`. However, the current requirement file fails to install `jq`:
```
      jq.c:12085:17: warning: assignment to ‘PyObject *’ {aka ‘struct _object *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
      12085 |             ret = _PyGen_Send((PyGenObject*)yf, value == Py_None ? NULL : value);
            |                 ^
      jq.c:12090:17: warning: assignment to ‘PyObject *’ {aka ‘struct _object *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
      12090 |             ret = _PyGen_Send((PyGenObject*)yf, value == Py_None ? NULL : value);
            |                 ^
      jq.c: In function ‘__Pyx_Generator_Next’:
      jq.c:12174:17: warning: assignment to ‘PyObject *’ {aka ‘struct _object *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
      12174 |             ret = _PyGen_Send((PyGenObject*)yf, NULL);
            |                 ^
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for jq
Failed to build jq
ERROR: Could not build wheels for jq, which is required to install pyproject.toml-based projects

```

**Full error**: [output.zip](https://github.com/wazuh/wazuh-qa/files/8892571/output.zip)

It is required to include some logic to install libraries depending on the python version.
We could use the [`python_version`](https://pip.pypa.io/en/stable/reference/requirements-file-format/) environment makers

**Comment by fedepacher** [comment]
# Update 2022/06/23

## Windows Server 2016/2022

### Install requirements.txt
```
python3 -m pip install -r requirements.txt
```

<details>

<summary> Output </summary>

```
  Downloading cffi-1.14.6.tar.gz (475 kB)
     ---------------------------------------- 475.7/475.7 kB 4.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\qa\AppData\Local\Temp\pip-install-ufvisjha\cffi_8cba5ce532384348a5fe03ce2af70224\setup.py", line 127, in <module>
          if sys.platform == 'win32' and uses_msvc():
        File "C:\Users\qa\AppData\Local\Temp\pip-install-ufvisjha\cffi_8cba5ce532384348a5fe03ce2af70224\setup.py", line 105, in uses_msvc
          return config.try_compile('#ifndef _MSC_VER\n#error "not MSVC"\n#endif')
        File "C:\Users\qa\AppData\Local\Programs\Python\Python310\lib\distutils\command\config.py", line 225, in try_compile
          self._compile(body, headers, include_dirs, lang)
        File "C:\Users\qa\AppData\Local\Programs\Python\Python310\lib\distutils\command\config.py", line 132, in _compile
          self.compiler.compile([src], include_dirs=include_dirs)
        File "C:\Users\qa\AppData\Local\Programs\Python\Python310\lib\distutils\_msvccompiler.py", line 323, in compile
          self.initialize()
        File "C:\Users\qa\AppData\Local\Programs\Python\Python310\lib\distutils\_msvccompiler.py", line 220, in initialize
          vc_env = _get_vc_env(plat_spec)
        File "C:\Users\qa\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\msvc.py", line 316, in msvc14_get_vc_env
          return _msvc14_get_vc_env(plat_spec)
        File "C:\Users\qa\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\msvc.py", line 270, in _msvc14_get_vc_env
          raise distutils.errors.DistutilsPlatformError(
      distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
WARNING: There was an error checking the latest version of pip.
```
</details>
