### ISSUE TITLE
Unstable Agentd IT test_agentd_multi_server

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#3429]
| Version | Commit | Report
| --- | --- | --- |
| 4.4.0 | 52d556b | [agent_windows_html_report_Test_integration_B32632_20221008065327.zip](https://github.com/wazu/wazuh-qa/files/974406/agent_windows_html_report_Test_integration_B32632_20221008065327.zip)

### Description
Agentd `test_agentd_multi_server` recently fails for `v4.4.0`
```
================================== FAILURES ===================================
_____________ test_agentd_multi_server[server_down_fallback_tcp] ______________
test_agentd\test_agentd_multi_server.py:474: in test_agentd_multi_server
    log_monitor.start(timeout=tcase_timeout, callback=lambda x: wait_until(x, log_str))
C:\Python37\lib\site-packages\wazuh_testing-4.4.0-py3.7.egg\wazuh_testing\tools\monitoring.py:203: in start
    error_message=error_message).result()
C:\Python37\lib\site-packages\wazuh_testing-4.4.0-py3.7.egg\wazuh_testing\tools\monitoring.py:469: in start
    raise TimeoutError(error_message)
E   TimeoutError

During handling of the above exception, another exception occurred:
test_agentd\test_agentd_multi_server.py:476: in test_agentd_multi_server
    assert False, f"Expected message '{log_str}' never arrived! Stage: {stage+1}, message number: {index+1}"
E   AssertionError: Expected message 'Requesting a key from server: testServer1' never arrived! Stage: 1, message number: 1
E   assert False
---------------------------- Captured stdout setup ----------------------------


Saturday, October 8, 2022 6:15:00 AM







The Wazuh service was stopped successfully.



The Wazuh service is starting.

The Wazuh service was started successfully.



---------------------------- Captured stderr setup ----------------------------
2022-10-08 06:15:11,322 - wazuh_testing - ERROR - Not valid keys used.
----------------------------- Captured log setup ------------------------------
ERROR    wazuh_testing:remoted_sim.py:592 Not valid keys used.
---------------------------- Captured stdout call -----------------------------


The Wazuh service was stopped successfully.



The Wazuh service is starting.

The Wazuh service was started successfully.



- generated html file: file://C:\tmp\Test_integration_B32632_20221008065327\report.html -
=========================== short test summary info ===========================
FAILED test_agentd/test_agentd_multi_server.py::test_agentd_multi_server[server_down_fallback_tcp]
```

**Comment by fedepacher** [comment]
# Update 2022/10/20 

In a local environment if the timeout is increased the test works as expected but, after running the test on a Jenkins windows machine the following error has been achieved:

```
The Wazuh service was stopped successfully.

The Wazuh service is starting.----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 51712)
Traceback (most recent call last):
  File "C:\Python37\lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Python37\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Python37\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "C:\Python37\lib\site-packages\wazuh_testing\tools\monitoring.py", line 707, in handle
    self.request.sendall(response)
  File "C:\Python37\lib\ssl.py", line 1034, in sendall
    v = self.send(byte_view[count:])
  File "C:\Python37\lib\ssl.py", line 1003, in send
    return self._sslobj.write(data)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
----------------------------------------

The Wazuh service was started successfully.


```

```
The Wazuh service was stopped successfully.

----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 51713)
Traceback (most recent call last):
  File "C:\Python37\lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Python37\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Python37\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "C:\Python37\lib\site-packages\wazuh_testing\tools\monitoring.py", line 707, in handle
    self.request.sendall(response)
  File "C:\Python37\lib\ssl.py", line 1034, in sendall
    v = self.send(byte_view[count:])
  File "C:\Python37\lib\ssl.py", line 1003, in send
    return self._sslobj.write(data)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
----------------------------------------

The Wazuh service was started successfully.

```

This error may be caused because of the python version (`python 3.7`) but after upgrading the python version to 3.10 the following error is achieved

```
The Wazuh service was stopped successfully.

----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 51944)
Traceback (most recent call last):
  File "C:\Users\Jenkins\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 683, in process_request_thre
ad
    self.finish_request(request, client_address)
  File "C:\Users\Jenkins\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\Jenkins\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 747, in __init__
    self.handle()
  File "C:\Users\Jenkins\AppData\Local\Programs\Python\Python310\lib\site-packages\wazuh_testing\tools\monitoring.py", l
ine 707, in handle
    self.request.sendall(response)
  File "C:\Users\Jenkins\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1237, in sendall
    v = self.send(byte_view[count:])
  File "C:\Users\Jenkins\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1206, in send
    return self._sslobj.write(data)
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2396)
----------------------------------------
The Wazuh service is starting.

```

Due to this error, the `client.keys` file is not written. This may be the cause of `test_agentd_multi_server.py` fails.

**Comment by Rebits** [comment]
### Update - 27/10/2022
An unsuccessful attempt has been made to reproduce the described behavior. https://github.com/wazuh/wazuh-qa/issues/3429#issuecomment-1286039712

**Comment by Rebits** [comment]
## Update - 28/10/2022

Manual replication of the tests case

Windows agent log after testing: [ossec.log](https://github.com/wazuh/wazuh-qa/files/9887874/ossec.log)

**Comment by fedepacher** [comment]
# Update 2022/10/31

It has created the issue [#3536](https://github.com/wazuh/wazuh-qa/issues/3536) that aims to request an agentd test refactor as a `system` test in order to avoid simulators.

**Comment by jmv74211** [comment]
The unstable test has been skipped and a new refactor issues has been opened to fix it.
