### ISSUE TITLE
System tests not working on virtual environments

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#4509]
## Description

During the execution of the release issue https://github.com/wazuh/wazuh/issues/18873 on a local virtual environment _(vagrant machine)_ several scenarios were continuously failing, the same scenarios were executed on an EC2 machine with the same result. But when running the tests completely locally, everything works correctly, the tests passes.
Other teammates have faced same behavior on their end.

> **Note:** As this suite can only be run locally on _UNIX-like_ systems (because of ansible), people with Windows system will not be able to run it at all.

### Current behavior

Several tests are failing on virtualized systems and only works correctly when running locally.

### Expected behavior

The suite can be executed on local or virtual environments without having different behavior.

**Comment by pro-akim** [comment]
## Update
It is possible to see the following message trying to install wazuh_testing library in pip3

<details>
```
root@bigubuntu:/home/vagrant/wazuh-qa/deps/wazuh_testing# pip3 uninstall -y wazuh_testing && pip3 install .
WARNING: Skipping wazuh-testing as it is not installed.
Processing /home/vagrant/wazuh-qa/deps/wazuh_testing
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-vj4udnvc/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-vj4udnvc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-vj4udnvc/pip-egg-info
         cwd: /tmp/pip-req-build-vj4udnvc/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-vj4udnvc/setup.py", line 76, in <module>
        version=get_version(),
      File "/tmp/pip-req-build-vj4udnvc/setup.py", line 66, in get_version
        f = open(abs_file_path)
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-vj4udnvc/../../version.json'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
</details>

Further research should be performed.

**Comment by pro-akim** [comment]
## Update
In local machine, it has worked without issues.

```
(testing_wz_qa) akim@akim-PC:~/Desktop/wazuh-qa/deps/wazuh_testing$ python3 -m pip install .
Processing /home/akim/Desktop/wazuh-qa/deps/wazuh_testing
  Preparing metadata (setup.py) ... done
Using legacy 'setup.py install' for wazuh-testing, since package 'wheel' is not installed.
Installing collected packages: wazuh-testing
  Running setup.py install for wazuh-testing ... done
Successfully installed wazuh-testing-4.6.0
```

**Comment by pro-akim** [comment]
## Update
Ubuntu 22.04.2 LTS EC2 T3.Large 

Library could be installed:


```
ubuntu@ip-172-31-83-131:~/wazuh-qa/deps/wazuh_testing$ python3 -m pip install .
Defaulting to user installation because normal site-packages is not writeable
Processing /home/ubuntu/wazuh-qa/deps/wazuh_testing
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: wazuh-testing
  Building wheel for wazuh-testing (setup.py) ... done
  Created wheel for wazuh-testing: filename=wazuh_testing-4.8.0-py3-none-any.whl size=433777 sha256=7f91c4c701c57a8559352efb8e39b5034740043da38fad0797e74f3675f08675
  Stored in directory: /tmp/pip-ephem-wheel-cache-i7n6_a2q/wheels/4b/14/08/f1d4ecabc851db6fbfd5ab380719b9612972906b48ec6b0f61
Successfully built wazuh-testing
Installing collected packages: wazuh-testing
  WARNING: The scripts add-agents-client-keys, check-files, data-visualizer, qa-ctl, qa-docs, simulate-agents, simulate-api-load, stress_results_comparator, unsync-agents, wazuh-log-metrics, wazuh-metrics, wazuh-report and wazuh-statistics are installed in '/home/ubuntu/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed wazuh-testing-4.8
```.0

**Comment by pro-akim** [comment]
## Update

Ubuntu 22.04.2 LTS EC2 T3.Large 50GB SSD

After installing successfully all the libraries, and deploying the first environment (one_manager_agent_env)

The following error was raised:

<details>

```
self = <testinfra.utils.ansible_runner.AnsibleRunner object at 0x7fd11a2ccd90>, host = 'wazuh-agent1', module_name = 'command', module_args = 'mkdir testdir1', options = {'become': False, 'check': False}
cmd = 'ansible --tree %s -i %s -m %s --args %s %s', args = ['/tmp/tmpy37yj9hz', '/home/ubuntu/wazuh-qa/tests/system/provisioning/one_manager_agent/inventory.yml', 'command', 'mkdir testdir1', 'wazuh-agent1']
options_cli = '', options_args = [], d = '/tmp/tmpy37yj9hz'

    def run_module(self, host, module_name, module_args, **options):
        cmd, args = 'ansible --tree %s', [None]
        if self.inventory_file:
            cmd += ' -i %s'
            args += [self.inventory_file]
        cmd += ' -m %s'
        args += [module_name]
        if module_args:
            cmd += ' --args %s'
            args += [module_args]
        options_cli, options_args = self.options_to_cli(options)
        if options_cli:
            cmd += ' ' + options_cli
            args.extend(options_args)
        cmd += ' %s'
        args += [host]
        with tempfile.TemporaryDirectory() as d:
            args[0] = d
>           out = local.run_expect([0, 2, 8], cmd, *args)
E           AssertionError: Unexpected exit code 4 for CommandResult(command=b"ansible --tree /tmp/tmpy37yj9hz -i /home/ubuntu/wazuh-qa/tests/system/provisioning/one_manager_agent/inventory.yml -m command --args 'mkdir testdir1' wazuh-agent1", exit_status=4, stdout=b'wazuh-agent1 | UNREACHABLE! => {\n    "changed": false,\n    "msg": "Failed to create temporary directory. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \\"/tmp\\", for more error information use -vvv. Failed command was: ( umask 77 && mkdir -p \\"` echo ~/.ansible/tmp `\\"&& mkdir \\"` echo ~/.ansible/tmp/ansible-tmp-1694700620.6770027-46185-4003782513358 `\\" && echo ansible-tmp-1694700620.6770027-46185-4003782513358=\\"` echo ~/.ansible/tmp/ansible-tmp-1694700620.6770027-46185-4003782513358 `\\" ), exited with result 1",\n    "unreachable": true\n}\n', stderr=None)
E           assert 4 in [0, 2, 8]
E            +  where 4 = CommandResult(command=b"ansible --tree /tmp/tmpy37yj9hz -i /home/ubuntu/wazuh-qa/tests/system/provisioning/one_manager...-tmp-1694700620.6770027-46185-4003782513358 `\\" ), exited with result 1",\n    "unreachable": true\n}\n', stderr=None).rc

../../../venvs/venv/lib/python3.10/site-packages/testinfra/utils/ansible_runner.py:283: AssertionError

```

</details>

**Comment by pro-akim** [comment]
## Update
Installing all the python libraries and running the test as root could avoid the previous permission messages.

Test with four_manager_disconnected_node_env

<details>

```
PLAY RECAP ************************************************************************************************************************************************************************
localhost                  : ok=13   changed=7    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
wazuh-agent1               : ok=8    changed=7    unreachable=0    failed=0    skipped=2    rescued=0    ignored=0   
wazuh-agent2               : ok=8    changed=7    unreachable=0    failed=0    skipped=2    rescued=0    ignored=0   
wazuh-master               : ok=13   changed=12   unreachable=0    failed=0    skipped=2    rescued=0    ignored=0   
wazuh-worker1              : ok=12   changed=11   unreachable=0    failed=0    skipped=2    rescued=0    ignored=0   
wazuh-worker2              : ok=12   changed=11   unreachable=0    failed=0    skipped=2    rescued=0    ignored=0   
wazuh-worker3              : ok=12   changed=11   unreachable=0    failed=0    skipped=2    rescued=0    ignored=0  
```

</details>

Test result:

<details>

```
root@ip-172-31-82-126:/home/ubuntu/wazuh-qa/tests/system# python3 -m pytest -m four_manager_disconnected_node_env
=============================================================================== test session starts ===============================================================================
platform linux -- Python 3.10.12, pytest-7.1.2, pluggy-1.3.0
rootdir: /home/ubuntu/wazuh-qa/tests/system, configfile: pytest.ini
plugins: testinfra-5.0.0, html-3.1.1, metadata-3.0.0
collected 144 items / 142 deselected / 2 selected                                                                                                                                 

test_cluster/test_agent_groups/test_agent_groups_new_cluster_node.py ..                                                                                                     [100%]
```


</details>

**Comment by pro-akim** [comment]
## Update

Testing different environments ...

**Comment by pro-akim** [comment]
## Conclusion

1. VM with ansible did not work for system tests.

2. EC2

  After research performed in:
  - https://github.com/wazuh/wazuh-qa/issues/4525


| Test | Environment |
|-----|-----|
|||
|||
|||
|||
Agentless_cluster


Big_cluster_40_agents


Four_manager_disconnected_node
One_manager_agent
Manager_agent
Enrollment_cluster
Basic_cluster

**Comment by verdx** [comment]
# Review 
Some changes have been asked in issue https://github.com/wazuh/wazuh-qa/issues/4525, whose conclusion directly changes this one, this issue is now also waiting for those changes.

**Comment by verdx** [comment]
GJ, LGTM!

**Comment by pro-akim** [comment]
## Update
All related issues have been addressed
