### ISSUE TITLE
FIM Test Fails for Windows Agents

### ISSUE THREAD

**Issue by rafabailon** [wazuh/wazuh-qa#4839]
# Description

During the tests of [Release 4.8.0 - Alpha 2 - Integration tests](https://github.com/wazuh/wazuh/issues/21399) I have detected an error in Windows Agent. The specific error is 

```bash
ERROR    wazuh_testing:monitoring.py:466 TimeoutError was raised because a single 'modified' event was expected for ['c:\\testdirectory_5\\testfile0'] but was not detected.
```

The error has been detected in the FIM tests.

<details>
  <summary>Pipeline Error</summary>
  <br/>

```bash
11:59:33  TASK [Launch windows pytests] **************************************************
11:59:33  task path: /home/ec2-user/workspace/Test_integration/quality/tests/integration/test_integration.yaml:37
11:59:33  fatal: [ID2_B45851_Test_integration_windows_agent]: FAILED! => {
11:59:33      "ansible_async_watchdog_pid": 2808,
11:59:33      "ansible_job_id": "905546570871.1016",
11:59:33      "changed": true,
11:59:33      "cmd": "powershell.exe -",
11:59:33      "delta": "0:25:48.621535",
11:59:33      "end": "2024-01-15 10:58:40.488711",
11:59:33      "failed_when_result": true,
11:59:33      "finished": 1,
11:59:33      "rc": 1,
11:59:33      "results_file": "C:\\Users\\Jenkins\\.ansible_async\\905546570871.1016",
11:59:33      "start": "2024-01-15 10:32:51.867175",
11:59:33      "started": 1
11:59:33  }
11:59:33  
11:59:33  MSG:
11:59:33  
11:59:33  non-zero return code
11:59:33  Using module file /usr/local/lib/python3.7/site-packages/ansible/modules/windows/win_stat.ps1
11:59:33  Pipelining is enabled.
11:59:33  <172.31.4.162> ESTABLISH WINRM CONNECTION FOR USER: Jenkins on PORT 5986 TO 172.31.4.162
11:59:33  EXEC (via pipeline wrapper)
11:59:37  <172.31.4.162> FETCH "C:\tmp\Test_integration_B45851_20240115110601\pytest_plain_report.txt" TO "/home/ec2-user/workspace/Test_integration/windows_agent_tests_Test_integration_B45851_20240115110601.txt"
...
11:59:45  PLAY RECAP *********************************************************************
11:59:45  ID2_B45851_Test_integration_windows_agent : ok=3    changed=3    unreachable=0    failed=1    skipped=8    rescued=0    ignored=0   
11:59:45  
11:59:45  Playbook run took 0 days, 0 hours, 26 minutes, 57 seconds
11:59:45  FATAL: command execution failed
11:59:45  hudson.AbortException: Ansible playbook execution failed
11:59:45  	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:262)
11:59:45  	at org.jenkinsci.plugins.ansible.workflow.AnsiblePlaybookStep$AnsiblePlaybookExecution.run(AnsiblePlaybookStep.java:430)
11:59:45  	at org.jenkinsci.plugins.ansible.workflow.AnsiblePlaybookStep$AnsiblePlaybookExecution.run(AnsiblePlaybookStep.java:351)
11:59:45  	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
11:59:45  	at hudson.security.ACL.impersonate2(ACL.java:449)
11:59:45  	at hudson.security.ACL.impersonate(ACL.java:461)
11:59:45  	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
11:59:45  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
11:59:45  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
11:59:45  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
11:59:45  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
11:59:45  	at java.base/java.lang.Thread.run(Thread.java:829)
11:59:45  [Pipeline] echo
11:59:45  hudson.AbortException: Ansible playbook execution failed
11:59:45  
11:59:45  [Pipeline] }
11:59:45  [Pipeline] // stage
11:59:45  [Pipeline] }
11:59:45  Failed in branch windows_agent
```

</details>

<details>
  <summary>Error in the Logs</summary>
  <br/>

```bash
================================== FAILURES ===================================
_ test_checkers[get_configuration3-c:\\testdirectory_5-file_attrs11-tags_to_apply11-True-test_folders0] _

file_path = 'c:\\testdirectory_5', file_attrs = {'check_mtime'}
tags_to_apply = {'check_just_one_yes'}, triggers_modification = True
create_monitored_folders_module = None
test_folders = ['c:\\testdirectory_1', 'c:\\testdirectory_2', 'c:\\testdirectory_3', 'c:\\testdirectory_4', 'c:\\testdirectory_5']
get_configuration = {'apply_to_modules': ['test_file_checkers'], 'metadata': {'directory_1': 'c:\\testdirectory_1', 'directory_2': 'c:\\te...: 'syscollector'}], 'elements': [{'disabled': {'value': 'yes'}}], 'section': 'wodle'}], 'tags': ['check_just_one_yes']}
configure_environment = None, restart_syscheckd = None
wait_for_fim_start = None

    @pytest.mark.parametrize('test_folders', [test_folders], ids='', scope='module')
    @pytest.mark.parametrize('file_path, file_attrs, tags_to_apply, triggers_modification', [
        (directory_1, file_all_attrs, {'check_all_yes'}, True),
        (directory_1, set(), {'check_all_no'}, False),
        (directory_1, file_attrs_no_hash_sha1, {'check_just_one_no'}, True),
        (directory_2, file_attrs_no_hash_md5, {'check_just_one_no'}, True),
        (directory_3, file_attrs_no_hash_sha256, {'check_just_one_no'}, True),
        (directory_4, file_attrs_no_size, {'check_just_one_no'}, True),
        (directory_5, file_attrs_no_mtime, {'check_just_one_no'}, True),
        (directory_1, {CHECK_SHA1SUM}, {'check_just_one_yes'}, True),
        (directory_2, {CHECK_MD5SUM}, {'check_just_one_yes'}, True),
        (directory_3, [CHECK_SHA256SUM], {'check_just_one_yes'}, True),
        (directory_4, {CHECK_SIZE}, {'check_just_one_yes'}, True),
        (directory_5, {CHECK_MTIME}, {'check_just_one_yes'}, True),
    ])
    def test_checkers(file_path, file_attrs, tags_to_apply, triggers_modification, create_monitored_folders_module,
                      test_folders, get_configuration, configure_environment, restart_syscheckd, wait_for_fim_start):
        '''
        description: Check if the 'wazuh-syscheckd' daemon adds in the generated events the 'check_' specified in
                     the configuration. These checks are attributes indicating that a monitored directory entry has
                     been modified. For example, if 'check_all=yes' and 'check_perm=no' are set for the same entry,
                     'syscheck' must send an event containing every possible 'check_' except the perms.
                     For this purpose, the test will monitor a directory using the 'check_all' attribute in
                     conjunction with one or more 'check_' on the same directory, having 'check_all' to 'yes' and the other
                     one to 'no'. Then it will make directory operations inside it, and finally, the test
                     will verify that the FIM events generated contain only the fields of the 'checks' specified for
                     the monitored keys/values.
    
        wazuh_min_version: 4.2.0
    
        tier: 1
    
        parameters:
            - file_path:
                type: str
                brief: Path of the directory that will be created under the root directory.
            - file_attrs:
                type: set
                brief: Set of options that are expected for directory events.
            - tags_to_apply:
                type: set
                brief: Run test if match with a configuration identifier, skip otherwise.
            - triggers_modification:
                type: bool
                brief: Specify if the given options generate file events.
            - create_monitored_folders_module:
                type: fixture
                brief: Create a given list of folders when the module starts. Delete the folders at the end of the module.
            - test_folders:
                type: dict
                brief: List of folders to be created for monitoring.
            - get_configuration:
                type: fixture
                brief: Get configurations from the module.
            - configure_environment:
                type: fixture
                brief: Configure a custom environment for testing.
            - restart_syscheckd:
                type: fixture
                brief: Clear the 'ossec.log' file and start a new monitor.
            - wait_for_fim_start:
                type: fixture
                brief: Wait for realtime start, whodata start, or end of initial FIM scan.
    
        assertions:
            - Verify that the FIM events generated contain only the 'check_' fields specified in the configuration.
    
        input_description: Different test cases are contained in an external YAML file (wazuh_check_all.yaml)
                           which includes configuration settings for the 'wazuh-syscheckd' daemon. Those are
                           combined with the testing directories to be monitored defined in the module.
    
        expected_output:
            - r'.*Sending FIM event: (.+)$' ('added', 'modified', and 'deleted' events)
    
        tags:
            - realtime
            - time_travel
        '''
        check_apply_test(tags_to_apply, get_configuration['tags'])
    
        # Test files checks.
>       regular_file_cud(file_path, wazuh_log_monitor, min_timeout=global_parameters.default_timeout,
                         options=file_attrs, triggers_modified_event=triggers_modification, escaped=True)

test_fim\test_files\test_file_checks\test_file_checkers.py:211: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
C:\Python311\Lib\site-packages\wazuh_testing\modules\fim\utils.py:756: in regular_file_cud
    event_checker.fetch_and_check('modified', min_timeout=min_timeout, triggers_event=triggers_event,
C:\Python311\Lib\site-packages\wazuh_testing\modules\fim\classes.py:233: in fetch_and_check
    self.events = self.fetch_events(min_timeout, triggers_event, extra_timeout, error_message=error_msg)
C:\Python311\Lib\site-packages\wazuh_testing\modules\fim\classes.py:246: in fetch_events
    result = self.log_monitor.start(timeout=max(len(self.file_list) * 0.01, min_timeout),
C:\Python311\Lib\site-packages\wazuh_testing\tools\monitoring.py:202: in start
    self._result = monitor.start(timeout=timeout, callback=callback, accum_results=accum_results,
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <wazuh_testing.tools.monitoring.QueueMonitor object at 0x000001FE533098D0>
timeout = 10
callback = <function callback_detect_file_modified_event at 0x000001FE522960C0>
accum_results = 1, update_position = True, timeout_extra = 0
error_message = "TimeoutError was raised because a single 'modified' event was expected for ['c:\\\\testdirectory_5\\\\testfile0'] but was not detected."

    def start(self, timeout=-1, callback=_callback_default, accum_results=1, update_position=True, timeout_extra=0,
              error_message=''):
        """Start the queue monitoring until the stop method is called."""
        if not self._continue:
            self._continue = True
            self._abort = False
            result = None
    
            while self._continue:
                if self._abort:
                    self.stop()
                    if error_message:
                        logger.error(error_message)
                        logger.error(f"Results accumulated: "
                                     f"{len(result) if isinstance(result, list) else 0}")
                        logger.error(f"Results expected: {accum_results}")
>                   raise TimeoutError(error_message)
E                   TimeoutError: TimeoutError was raised because a single 'modified' event was expected for ['c:\\testdirectory_5\\testfile0'] but was not detected.

C:\Python311\Lib\site-packages\wazuh_testing\tools\monitoring.py:470: TimeoutError
---------------------------- Captured stderr call -----------------------------
2024-01-15 10:36:41,035 - wazuh_testing - INFO - Creating file c:\testdirectory_5\testfile0 of regular type
2024-01-15 10:36:41,650 - wazuh_testing - INFO - 'added' event detected as expected.

2024-01-15 10:36:41,650 - wazuh_testing - INFO - - Changing content of c:\testdirectory_5\testfile0
2024-01-15 10:36:51,757 - wazuh_testing - ERROR - TimeoutError was raised because a single 'modified' event was expected for ['c:\\testdirectory_5\\testfile0'] but was not detected.
2024-01-15 10:36:51,757 - wazuh_testing - ERROR - Results accumulated: 0
2024-01-15 10:36:51,757 - wazuh_testing - ERROR - Results expected: 1
------------------------------ Captured log call ------------------------------
INFO     wazuh_testing:file.py:750 Creating file c:\testdirectory_5\testfile0 of regular type
INFO     wazuh_testing:utils.py:746 'added' event detected as expected.

INFO     wazuh_testing:file.py:775 - Changing content of c:\testdirectory_5\testfile0
ERROR    wazuh_testing:monitoring.py:466 TimeoutError was raised because a single 'modified' event was expected for ['c:\\testdirectory_5\\testfile0'] but was not detected.
ERROR    wazuh_testing:monitoring.py:467 Results accumulated: 0
ERROR    wazuh_testing:monitoring.py:469 Results expected: 1
- generated html file: file://C:\tmp\Test_integration_B45851_20240115110601\report.html -
=========================== short test summary info ===========================
FAILED test_fim/test_files/test_file_checks/test_file_checkers.py::test_checkers[get_configuration3-c:\\testdirectory_5-file_attrs11-tags_to_apply11-True-test_folders0]
=== 1 failed, 88 passed, 568 skipped, 734 deselected in 1545.14s (0:25:45) ====
```

</details>

# Evidences

- **Report:** [agent_windows_html_report_Test_integration_B45851.zip](https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45851/agent_windows_html_report_Test_integration_B45851.zip)
- **Build:** https://ci.wazuh.info/job/Test_integration/45817/

The first build did not generate the `.zip` file so I did a re-launch.

- **Another Build:** https://ci.wazuh.info/job/Test_integration/45851/

**Comment by jotacarma90** [comment]
## Update 18/01/2024

PR created with the possible solution, researching format and methodology of this repository to validate all checks.

**Comment by jotacarma90** [comment]
## Testing solution


Jenkins build success:
https://ci.wazuh.info/job/Test_integration/45871/
