### ISSUE TITLE
DTT1 - Iteration 3 - Allocation module - Allow subscribing to a marketplace AMI for AWS deployments

### ISSUE THREAD

**Issue by c-bordon** [wazuh/wazuh-qa#4928]
It is necessary to add the possibility of subscribing to AMIs from the marketplace, when necessary, at the moment it happened to us when trying to use the `openSUSE` image

```console
cbordon@cbordon-MS-7C88:~/Documents/wazuh/repositorios/wazuh-qa/deployability$ python3 launchers/allocation.py --composite-name linux-opensuse-15-amd64 --provider aws --size large
[2024-02-07 13:15:22] [INFO] ALLOCATOR: Creating instance at /tmp/wazuh-qa
[2024-02-07 13:15:22] [DEBUG] ALLOCATOR: No config provided. Generating from payload
[2024-02-07 13:15:22] [DEBUG] ALLOCATOR: Creating base directory: /tmp/wazuh-qa/AWS-0086354B-4F45-4609-AE1F-6C298B0CF481
Traceback (most recent call last):
  File "/home/cbordon/Documents/wazuh/repositorios/wazuh-qa/deployability/launchers/allocation.py", line 30, in <module>
    main()
  File "/home/cbordon/Documents/wazuh/repositorios/wazuh-qa/deployability/launchers/allocation.py", line 26, in main
    Allocator.run(InputPayload(**vars(parse_arguments())))
  File "/home/cbordon/Documents/wazuh/repositorios/wazuh-qa/deployability/modules/allocation/allocation.py", line 31, in run
    return cls.__create(payload)
  File "/home/cbordon/Documents/wazuh/repositorios/wazuh-qa/deployability/modules/allocation/allocation.py", line 50, in __create
    instance = provider.create_instance(
  File "/home/cbordon/Documents/wazuh/repositorios/wazuh-qa/deployability/modules/allocation/generic/provider.py", line 65, in create_instance
    return cls._create_instance(base_dir, params, config)
  File "/home/cbordon/Documents/wazuh/repositorios/wazuh-qa/deployability/modules/allocation/aws/provider.py", line 57, in _create_instance
    instance_id = cls.__create_ec2_instance(config)
  File "/home/cbordon/Documents/wazuh/repositorios/wazuh-qa/deployability/modules/allocation/aws/provider.py", line 107, in __create_ec2_instance
    instance = client.create_instances(ImageId=config.ami,
  File "/home/cbordon/.local/lib/python3.10/site-packages/boto3/resources/factory.py", line 580, in do_action
    response = action(self, *args, **kwargs)
  File "/home/cbordon/.local/lib/python3.10/site-packages/boto3/resources/action.py", line 88, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/cbordon/.local/lib/python3.10/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/cbordon/.local/lib/python3.10/site-packages/botocore/client.py", line 983, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (OptInRequired) when calling the RunInstances operation: In order to use this AWS Marketplace product you need to accept terms and subscribe. To do so please visit https://aws.amazon.com/marketplace/pp?sku=147aomaaws9zx4er41jp3mozy
```

**Comment by c-bordon** [comment]
## Update report

This is not a fix that must be done by code, it is necessary to enter the URL indicated by the module itself and subscribe to the AMI in the account in question to then be able to use the AMI


![Screenshot_20240321_165004](https://github.com/wazuh/wazuh-qa/assets/64099752/e86256e2-3a7b-443a-baec-23617c836ec7)

**Comment by c-bordon** [comment]
All AMIs are reviewed and the necessary ones are subscribed, no changes were necessary at the code level.
