### ISSUE TITLE
Data visualization script fails to generate certain graphs

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh-qa#4975]
## Description

During the research performed in https://github.com/wazuh/wazuh-jenkins/issues/4748, we found that the data visualization [script](https://github.com/wazuh/wazuh-qa/blob/master/deps/wazuh_testing/wazuh_testing/scripts/data_visualizations.py) used to generate the graphics from the data collected is not working when used on the log or statistics (except logcollectord) files.

> Artifacts: [artifacts.zip](https://github.com/wazuh/wazuh-qa/files/14331652/artifacts.zip)

These were the errors found:

<details><summary>Type error</summary>

```console
Traceback (most recent call last):
  File "/usr/local/bin/data-visualizer", line 33, in <module>
    sys.exit(load_entry_point('wazuh-testing==4.8.0', 'console_scripts', 'data-visualizer')())
  File "/usr/local/lib/python3.9/site-packages/wazuh_testing-4.8.0-py3.9.egg/wazuh_testing/scripts/data_visualizations.py", line 33, in main
    dv.plot()
  File "/usr/local/lib/python3.9/site-packages/wazuh_testing-4.8.0-py3.9.egg/wazuh_testing/tools/performance/visualization.py", line 305, in plot
    self._plot_cluster_dataset()
  File "/usr/local/lib/python3.9/site-packages/wazuh_testing-4.8.0-py3.9.egg/wazuh_testing/tools/performance/visualization.py", line 286, in _plot_cluster_dataset
    self._plot_data(elements=list(self.dataframe['activity'].unique()), generic_label='Managers')
  File "/usr/local/lib/python3.9/site-packages/wazuh_testing-4.8.0-py3.9.egg/wazuh_testing/tools/performance/visualization.py", line 226, in _plot_data
    statistics=DataVisualizer._get_statistics(
  File "/usr/local/lib/python3.9/site-packages/wazuh_testing-4.8.0-py3.9.egg/wazuh_testing/tools/performance/visualization.py", line 141, in _get_statistics
    statistics += f"Mean: {round(pd.DataFrame.mean(df), 3)}\n"
  File "/usr/local/lib/python3.9/site-packages/pandas/core/frame.py", line 11666, in mean
    result = super().mean(axis, skipna, numeric_only, **kwargs)
TypeError: super(type, obj): obj must be an instance or subtype of type
```

</details>

<details><summary>Key error</summary>

```console
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3802, in get_loc
    return self._engine.get_loc(casted_key)
  File "index.pyx", line 153, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 182, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'queued_msgs'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/bin/data-visualizer", line 33, in <module>
    sys.exit(load_entry_point('wazuh-testing==4.8.0', 'console_scripts', 'data-visualizer')())
  File "/usr/local/lib/python3.9/site-packages/wazuh_testing-4.8.0-py3.9.egg/wazuh_testing/scripts/data_visualizations.py", line 33, in main
    dv.plot()
  File "/usr/local/lib/python3.9/site-packages/wazuh_testing-4.8.0-py3.9.egg/wazuh_testing/tools/performance/visualization.py", line 299, in plot
    self._plot_remoted_dataset()
  File "/usr/local/lib/python3.9/site-packages/wazuh_testing-4.8.0-py3.9.egg/wazuh_testing/tools/performance/visualization.py", line 263, in _plot_remoted_dataset
    self._plot_data(elements=columns, title=title, generic_label=element)
  File "/usr/local/lib/python3.9/site-packages/wazuh_testing-4.8.0-py3.9.egg/wazuh_testing/tools/performance/visualization.py", line 243, in _plot_data
    self._basic_plot(ax, self.dataframe[element], label=element, color=color)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/frame.py", line 4090, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3809, in get_loc
    raise KeyError(key) from err
KeyError: 'queued_msgs'
```

</details>

We should investigate the root cause of the failures, apply a fix and verify that all graphs are generated successfully.

**Comment by GGP1** [comment]
## Update

I took some artifacts from a recent build and tested the data graphic generation like the pipeline does. Cluster, remoted and analysisd were failing but after applying some fixes they were generated successfully.

<details><summary>Binaries 🟢 </summary>

Artifacts: [binaries.zip](https://github.com/wazuh/wazuh-qa/files/14386180/binaries.zip)

```console
(venv) gasti@pop-os:~/work/wazuh-qa$ data-visualizer -s wazuh-analysisd.csv wazuh-apid_child_1.csv wazuh-apid_child_2.csv wazuh-apid_child_3.csv wazuh-apid.csv wazuh_clusterd_child_1.csv wazuh_clusterd_child_2.csv wazuh_clusterd.csv wazuh-logcollector.csv wazuh-remoted.csv -t binary -d /tmp/test -n binaries
(venv) gasti@pop-os:~/work/wazuh-qa$ ls /tmp/test/
binaries_CPU.svg              binaries_Disk_Write_Speed.svg  binaries_PSS.svg       binaries_SWAP.svg  binaries_Write_Ops.svg
binaries_Disk_Read_Speed.svg  binaries_Disk_Written.svg      binaries_Read_Ops.svg  binaries_USS.svg
binaries_Disk_Read.svg        binaries_FD.svg                binaries_RSS.svg       binaries_VMS.svg
```

</details>

<details><summary>Cluster (fixed) 🟢 </summary>

Previously failing, after some changes I was able to generate them successfully. 

Artifacts: [cluster.zip](https://github.com/wazuh/wazuh-qa/files/14386292/cluster.zip)

```console
(venv) gasti@pop-os:~/work/wazuh-qa$ data-visualizer -s agent-groups_send.csv agent-info_sync.csv integrity_check.csv integrity_sync.csv -t cluster -d /tmp/test -n cluster
(venv) gasti@pop-os:~/work/wazuh-qa$ ls /tmp/test
cluster_agent-groups_send.svg  cluster_agent-info_sync.svg  cluster_integrity_check.svg  cluster_integrity_sync.svg
```

</details>

<details><summary>Logcollector 🟢 </summary>

Artifacts: [logcollector.zip](https://github.com/wazuh/wazuh-qa/files/14386443/logcollector.zip)

```console
(venv) gasti@pop-os:~/work/wazuh-qa$ data-visualizer -s active-responses_log.csv -t logcollector -d /tmp/test -n active-responses_log
(venv) gasti@pop-os:~/work/wazuh-qa$ data-visualizer -s audit_log.csv -t logcollector -d /tmp/test -n audit_log
(venv) gasti@pop-os:~/work/wazuh-qa$ data-visualizer -s df.csv -t logcollector -d /tmp/test -n df
(venv) gasti@pop-os:~/work/wazuh-qa$ data-visualizer -s last.csv -t logcollector -d /tmp/test -n last
(venv) gasti@pop-os:~/work/wazuh-qa$ data-visualizer -s maillog.csv -t logcollector -d /tmp/test -n maillog
(venv) gasti@pop-os:~/work/wazuh-qa$ data-visualizer -s messages.csv -t logcollector -d /tmp/test -n messages
(venv) gasti@pop-os:~/work/wazuh-qa$ data-visualizer -s netstat.csv -t logcollector -d /tmp/test -n netstat
(venv) gasti@pop-os:~/work/wazuh-qa$ data-visualizer -s secure.csv -t logcollector -d /tmp/test -n secure
(venv) gasti@pop-os:~/work/wazuh-qa$ ls /tmp/test
active-responses_log_bytes.svg         df_bytes.svg           maillog_bytes.svg          netstat_bytes.svg
active-responses_log_events.svg        df_events.svg          maillog_events.svg         netstat_events.svg
active-responses_log_target_drops.svg  df_target_drops.svg    maillog_target_drops.svg   netstat_target_drops.svg
audit_log_bytes.svg                    last_bytes.svg         messages_bytes.svg         secure_bytes.svg
audit_log_events.svg                   last_events.svg        messages_events.svg        secure_events.svg
audit_log_target_drops.svg             last_target_drops.svg  messages_target_drops.svg  secure_target_drops.svg
```

</details>

<details><summary>Remoted (fixed) 🟢 </summary>

Previously failing, after removing a header that was not in the .csv file it worked.

Artifacts: [remoted.zip](https://github.com/wazuh/wazuh-qa/files/14386519/remoted.zip)

```console
(venv) gasti@pop-os:~/work/wazuh-qa$ data-visualizer -s wazuh-remoted_stats.csv -t remote -d /tmp/test -n remoted
(venv) gasti@pop-os:~/work/wazuh-qa$ ls /tmp/test
remoted_events_info.svg  remoted_queue_size.svg  remoted_recv_bytes.svg  remoted_tcp_sessions.svg
```

</details>

<details><summary>Analysisd (fixed) 🟢 </summary>

Previously failing, after removing some headers that were not in the .csv file it worked.

Artifacts: [analysisd.zip](https://github.com/wazuh/wazuh-qa/files/14386644/analysisd.zip)

```console
(venv) gasti@pop-os:~/work/wazuh-qa$ data-visualizer -s wazuh-analysisd_stats.csv -t analysis -d /tmp/test -n analysisd
(venv) gasti@pop-os:~/work/wazuh-qa$ ls /tmp/test
analysisd_alerts_info.svg  analysisd_decoded_events.svg  analysisd_queue_usage.svg
```

</details>

**Comment by GGP1** [comment]
## Update

During https://github.com/wazuh/wazuh-qa/issues/4890, some changes were made to the statistics generation script which now gathers data from the API. The files generated from the API information are completely different to the ones used previously and there were no changes to the data visualization script, meaning that their graphics generation will fail.

I created the following issue to solve this: https://github.com/wazuh/wazuh-qa/issues/5022

**Comment by GGP1** [comment]
## Update

I launched a build with the changes in the QA package but the graphics are not being generated because there have been several changes in the name of the columns of every file inside the `data` folder.

Build: https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/471

I will leave the issue on hold until we decide how to proceed.
