### ISSUE TITLE
Include install package retry logic in case of  unable to acquire the dpkg frontend lock

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#5415]
## Description
During the [Failures in Vulnerability Detection E2E Tests RC 2](https://github.com/wazuh/wazuh-qa/issues/5397#issuecomment-2124334542), it was observed that package installation or removal can intermittently fail due to unattended upgrades on target agents. To address this, we need to implement retry logic for package installation in such cases.

## Tasks
- [ ]  Enhance the `install_package` method in the `HostManager` to include retry logic when encountering errors such as `Unable to acquire the dpkg frontend lock` and similar issues across different endpoints.
 
 ## Validation
- [ ] Verify that the `install_package` method attempts to install the specified package multiple times when another package is being installed and holding the lock.

**Comment by Rebits** [comment]
Added the `dpkg frontend lock was locked by another process with pid` error to the list of errors that trigger an installation retry.
```
>>> hm.install_package('manager1', 'https://dl.grafana.com/oss/release/grafana_8.5.5_amd64.deb', system='ubuntu')
ERROR:root:Error installing https://dl.grafana.com/oss/release/grafana_8.5.5_amd64.deb in manager1: Retrying installation...
ERROR:root:Error installing https://dl.grafana.com/oss/release/grafana_8.5.5_amd64.deb in manager1: Retrying installation...
ERROR:root:Error installing https://dl.grafana.com/oss/release/grafana_8.5.5_amd64.deb in manager1: Retrying installation...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rebits/Wazuh/wazuh-qa/deps/wazuh_testing/wazuh_testing/tools/system.py", line 576, in install_package
    raise RuntimeError(f"Failed to install package in {host}: {result}")
RuntimeError: Failed to install package in manager1: {'changed': False, 'msg': 'dpkg --force-confdef --force-confold -i /home/qa/.ansible/tmp/ansible-tmp-1716393189.2474802-127512-68231285750961/grafana_8.5.5_amd64blw0ol37.deb failed', 'stderr': 'dpkg: error: dpkg frontend lock was locked by another process with pid 96659\nNote: removing the lock file is always wrong, and can end up damaging the\nlocked area and the entire system. See <https://wiki.debian.org/Teams/Dpkg/FAQ>.\n', 'stderr_lines': ['dpkg: error: dpkg frontend lock was locked by another process with pid 96659', 'Note: removing the lock file is always wrong, and can end up damaging the', 'locked area and the entire system. See <https://wiki.debian.org/Teams/Dpkg/FAQ>.'], 'stdout': '', 'stdout_lines': []}
>>> hm.install_package('manager1', 'https://dl.grafana.com/oss/release/grafana_8.5.5_amd64.deb', system='ubuntu')
{'changed': True, 'stderr': '', 'stderr_lines': [], 'stdout': 'Selecting previously unselected package grafana.\n(Reading database ... 143746 files and directories currently installed.)\nPreparing to unpack .../grafana_8.5.5_amd644ug_11eb.deb ...\nUnpacking grafana (8.5.5) ...\nSetting up grafana (8.5.5) ...\nRestarting grafana-server service... OK\n', 'stdout_lines': ['Selecting previously unselected package grafana.', '(Reading database ... 143746 files and directories currently installed.)', 'Preparing to unpack .../grafana_8.5.5_amd644ug_11eb.deb ...', 'Unpacking grafana (8.5.5) ...', 'Setting up grafana (8.5.5) ...', 'Restarting grafana-server service... OK']}
```
