### ISSUE TITLE
Unable to deploy macOS machines due to permissions error in DTT testing

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh-qa#5829]
| Version | Revision | Production/Development | Component | Install type |
|:--:|:--:|:--:|:--:|:--:|
|  v4.9.2-rc1  |  1  |  Development  |  Allocation module  | - | 

## Description

During the tests performed at https://github.com/wazuh/wazuh/issues/26614, the deployment of macOS hosts failed. 
The following log could be observed (same type in all macOS agents):

```
[31m[2024-10-29 14:46:56] [ERROR] [477704] [ThreadPoolExecutor-0_6] [jobflow]: [allocate-macos-agent-macos-sequoia-15-amd64] Task failed with error: Error executing process task Traceback (most recent call last):
  File "/home/akim/Desktop/branch_management/wazuh-qa/deployability/modules/allocation/vagrant/provider.py", line 350, in __remote_host
    server_ip = client.get_secret_value(SecretId='devops_macstadium_intel_ip')['SecretString']
  File "/home/akim/Desktop/venvs/dtt1/lib/python3.10/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/akim/Desktop/venvs/dtt1/lib/python3.10/site-packages/botocore/client.py", line 983, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDeniedException) when calling the GetSecretValue operation: Access to KMS is not allowed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/akim/Desktop/branch_management/wazuh-qa/deployability/modules/allocation/main.py", line 39, in <module>
    main()
  File "/home/akim/Desktop/branch_management/wazuh-qa/deployability/modules/allocation/main.py", line 35, in main
    Allocator.run(InputPayload(**vars(parse_arguments())))
  File "/home/akim/Desktop/branch_management/wazuh-qa/deployability/modules/allocation/allocation.py", line 40, in run
    return cls.__create(payload)
  File "/home/akim/Desktop/branch_management/wazuh-qa/deployability/modules/allocation/allocation.py", line 59, in __create
    instance = provider.create_instance(
  File "/home/akim/Desktop/branch_management/wazuh-qa/deployability/modules/allocation/generic/provider.py", line 71, in create_instance
    return cls._create_instance(base_dir, params, config, ssh_key)
  File "/home/akim/Desktop/branch_management/wazuh-qa/deployability/modules/allocation/vagrant/provider.py", line 81, in _create_instance
    remote_host_parameters = cls.__remote_host(arch, 'create')
  File "/home/akim/Desktop/branch_management/wazuh-qa/deployability/modules/allocation/vagrant/provider.py", line 354, in __remote_host
    raise ValueError('Could not get macOS macStadium Intel server IP: ' + str(e) + '.')
ValueError: Could not get macOS macStadium Intel server IP: An error occurred (AccessDeniedException) when calling the GetSecretValue operation: Access to KMS is not allowed.
[0m
```

### Environment

branch v4.9.2-rc1

### Steps to reproduce

1. Clone wazuh-qa repository

2. Move to v4.9.2-rc1 branch

3. Follow the README in deployability

4. Use the following YAML:  [Test-agents-complete.yaml.txt](https://github.com/user-attachments/files/17556908/Test-agents-complete.yaml.txt)

### Current result

Deployment failure

### Expected result

No errors during deployment were expected

**Comment by c-bordon** [comment]
## Update report

This issue was generated by changes in the secrets configuration for this [issue](https://github.com/wazuh/wazuh-automation/issues/1376), the changes were reverted and access was reestablished.
