### ISSUE TITLE
Debian 12 failed in Deployability Tests

### ISSUE THREAD

**Issue by joaquinsgi** [wazuh/wazuh-qa#5832]
| Version | Revision | Production/Development | Component | Install type |
|:--:|:--:|:--:|:--:|:--:|
|  4.9.2  |  RC 1  |    |    | Download/Repository/Sources/Assistant | 

## Description

During the tests of Deployability: https://github.com/wazuh/wazuh/issues/26614, in the central component tests, the Debian 12 machine failed due to the following errors:
```
[2024-10-29 16:42:24,737] [ERROR] TESTER: The Wazuh manager's API port in debian-12 is closed
[2024-10-29 16:52:05,964] [ERROR] TESTER: The Wazuh manager port in debian-12 is closed
[2024-10-29 17:01:47,486] [ERROR] TESTER: The Wazuh manager agent enrollment port in debian-12 is closed
[2024-10-29 16:32:40,273] [ERROR] TESTER: The /var/ossec is not present in debian-12
```
It looks like it could not install the wazuh manager, and the port is closed.
After rebuilding with the same steps it did not have failures.

### Steps to reproduce

1. git clone git@github.com:wazuh/wazuh-qa.git
2. cd wazuh-qa
3. git checkout v4.9.2-rc1  
4. python3 -m venv env
5. source env/bin/activate  
6. pip3 install -r deployability/deps/requirements.txt
7. cd modules
8. pip3 uninstall -y jobflow && pip3 install .
9. Use: [test-CC-complete.yaml.txt](https://github.com/user-attachments/files/17560961/test-CC-complete.yaml.txt)
10. python3 -m jobflow modules/jobflow/examples/test-c-complete.yaml --threads X

### Current result

Failed test

### Expected result

Passed all tests

### Attachments

- Logs: 
    - [jobflow.log.txt](https://github.com/user-attachments/files/17560985/jobflow.log.txt)
    - [jobflow-rebuild.log.txt](https://github.com/user-attachments/files/17560986/jobflow-rebuild.log.txt)

**Comment by rauldpm** [comment]
Looking at the failed log provided, the Debian 12 install test failed (line 6300)

```
[2024-10-29 17:16:46,595] [ERROR] [28576] [ThreadPoolExecutor-0_0] [jobflow]: [run-central_components-linux-debian-12-amd64-tests] Task failed with error: Error executing process task /home/joaquinsgi/Desktop/Wazuh/repositories/wazuh-qa/jobflow/lib/python3.10/site-packages/paramiko/pkey.py:100: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "cipher": algorithms.TripleDES,
/home/joaquinsgi/Desktop/Wazuh/repositories/wazuh-qa/jobflow/lib/python3.10/site-packages/paramiko/transport.py:259: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "class": algorithms.TripleDES,
Traceback (most recent call last):
  File "/home/joaquinsgi/Desktop/Wazuh/repositories/wazuh-qa/deployability/modules/testing/main.py", line 29, in <module>
    Tester.run(InputPayload(**vars(parse_arguments())))
  File "/home/joaquinsgi/Desktop/Wazuh/repositories/wazuh-qa/deployability/modules/testing/testing.py", line 60, in run
    cls._run_tests(payload.tests, ansible, extra_vars)
  File "/home/joaquinsgi/Desktop/Wazuh/repositories/wazuh-qa/deployability/modules/testing/testing.py", line 94, in _run_tests
    raise Exception(f"Test {test} failed with error: {event['stdout']}")
Exception: Test install failed with error: [0;31mfatal: [localhost]: FAILED! => changed=true [0m
```

The scripts appears to be downloaded correctly, but then, the manager service is missing, as this test appears to be flaky, we need to replay it without destroy and access the Debian 12 so we can investigate the cause

**Comment by juliamagan** [comment]
It seems to be a flaky test, but we should investigate why it is flaky. Moving to a later release.

**Comment by pro-akim** [comment]
Analyzed here: https://github.com/wazuh/wazuh-qa-automation/issues/584

**Comment by juliamagan** [comment]
Related to https://github.com/wazuh/wazuh-qa-automation/issues/648
